services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: app-ts
      DB_USER: admin
      DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: app-ts
    volumes:
      - app-ts-data:/var/lib/postgres
    ports:
      - 8093:5432


volumes:
  app-ts-data:
